import { Geist, Geist_Mono } from "next/font/google";
import Sidebar from "../components/sidebar"; // Use TWO dots and lowercase if the file is sidebar.js
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-slate-50">
        <div className="flex">
          <Sidebar />
          {/* This 'children' represents whichever page the user is visiting */}
          <main className="lg:ml-64 flex-1 min-h-screen">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
